services:
  fastapi:
    image: paragbhardwajrelanto/fastapi:dev #replace with actual docker user id
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
  streamlit:
    image: paragbhardwajrelanto/streamlit:dev #replace with actual docker user id
    build:
      context: ./streamlit_app
      dockerfile: Dockerfile
    ports:
      - 8501:8501
    environment:
      API_URL: http://fastapi:8000